spring:
  application:
    name: spring-redis-example

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

    hikari:
      pool-name: production-pool
      maximum-pool-size: 5
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      data-source-properties:
        prepareThreshold: 0
        preparedStatementCacheQueries: 0

  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

redis:
  uri: ${REDIS_URI}